# Generated by Django 4.2.9 on 2024-04-23 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comingSoon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsuser',
            options={'ordering': ['email']},
        ),
        migrations.RemoveField(
            model_name='newsuser',
            name='name',
        ),
    ]
